{% set name = "pmdarima" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4aad8cb9d4f3d2bbf78a807d383e23f445dbf4691741b69c90655d932417a521

build:
  number: 3
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - cython >=0.29,!=0.29.18
    - joblib >=0.11
    - numpy ~=1.19.0
    - pandas >=0.19
    - python
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - setuptools <50.0.0
    - statsmodels >=0.11,!=0.12.0
    - urllib3
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pmdarima
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alkaline-ml/pmdarima
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities

extra:
  recipe-maintainers:
    - cdesouza21
