{% set name = "pmdarima" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a252ef19359d418aec5ebaeb76832c1934b4b680446bad46cdbf26775eb840a8

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29,!=0.29.18
    - numpy >=1.19.3
    - pip
    - python
  run:
    - cython >=0.29,!=0.29.18
    - joblib >=0.11
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19
    - python
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - setuptools >=38.6.0,!=50.0.0
    - statsmodels >=0.11,!=0.12.0
    - urllib3

test:
  imports:
    - pmdarima
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alkaline-ml/pmdarima
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities

extra:
  recipe-maintainers:
    - cdesouza21
