{% set name = "pmdarima" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b87f9d9f5b7dc2ddbd053687c2264e26ac98fd4118e843c7e9bc3dd7343e5c1a

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=1.21.2                         # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython >=0.29,!=0.29.18,!=0.29.31
    - numpy >=1.21.2
    - packaging >=17.1
    - pip
    - python
  run:
    - cython >=0.29,!=0.29.18,!=0.29.31
    - joblib >=0.11
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19
    - python
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - setuptools >=38.6.0,!=50.0.0
    - packaging >=17.1
    - statsmodels >=0.11,!=0.12.0
    - urllib3

test:
  source_files:
    - pmdarima
  imports:
    - pmdarima
  commands:
    - pip check
    - python setup.py develop
    - python -m pytest -v
  requires:
    - pip
    - pytest
    - matplotlib
    - pytest-mpl

about:
  home: https://github.com/alkaline-ml/pmdarima
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
