{% set name = "pmdarima" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b187a6524a470a1cc5866083c0c9e3f18a14037d99936d55d7474e48f4ea451e

build:
  number: 1
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - cython >=0.29,<0.29.18
    - joblib
    - numpy
    - pandas
    - python
    - scikit-learn
    - scipy
    - setuptools
    - statsmodels >=0.11,<0.12
    - urllib3
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pmdarima
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alkaline-ml/pmdarima
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities"

extra:
  recipe-maintainers:
    - cdesouza21 
